locators:
  login_button:
    xpath: "//*[@id='OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt15_block_wtLogin_wt13']"
    wait: timeouts.browser.small
  email_input:
    xpath: "//*[@id='OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt15_block_wtLogin_OutSystemsUIWeb_wt26_block_wtInput_wtUserNameInput']"
    wait: timeouts.browser.small
  password_input:
    xpath: "//*[@id='OutSystemsUIWeb_wt14_block_wtLogin_OutSystemsUIWeb_wt15_block_wtLogin_OutSystemsUIWeb_wt6_block_wtInput_wtPasswordInput']"
    wait: timeouts.browser.small
  incorrect_login:
    xpath: ".//div[@class='Feedback_Message_Error']"
    wait: timeouts.browser.medium
  new_movie:
      xpath: ".//*[@id='wt29_OutSystemsUIWeb_wt2_block_wtContent_wtActions_wt34']"
      wait: timeouts.browser.small