locators:
  goto_login:
    xpath: ".//*[@id='wt11_OutSystemsUIWeb_wt2_block_wtHeader_wtRight_wt4_wtLogin']"
    wait: timeouts.browser.small
  login_img:
    xpath: '/html/body/form/div[4]/div/header/div/div[1]/div[4]/div/div/img'
    wait: timeouts.browser.small
  login_user_text:
    xpath: ".//span[@class='loginusername'][contains(text(),'$0')]"
    wait: timeouts.browser.small
  new_movie:
    xpath: ".//*[@id='wt11_OutSystemsUIWeb_wt2_block_wtContent_wtActions_wt2']"
    wait: timeouts.browser.big
  movie_title:
    xpath: ".//td[contains(@class, 'TableRecords')]//a[contains(text(),'$0')]"
    wait: timeouts.browser.small
  movie_description:
    xpath: ".//td[contains(@class, 'TableRecords')][contains(text(),'$0')]"
    wait: timeouts.browser.small
  movie_saved_success:
    xpath: ".//div[@class='Feedback_Message_Success']"
    wait: timeouts.browser.medium
  people_tab:
    xpath: ".//*[@id='wt11_OutSystemsUIWeb_wt2_block_wtHeader_wtCenter_wt19_RichWidgets_wt2_block_wtMenuItem_wt11']"
    wait: timeouts.browser.small
  movie_search:
    xpath: ".//*[@id='wt11_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wt25']"
    wait: timeouts.browser.small
  search_button:
    xpath: "//*[@id='wt11_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wt26']"
    wait: timeouts.browser.small