locators:
  new_people_text:
    xpath: ".//*[@id='wt35_OutSystemsUIWeb_wt2_block_wtContent_wtTitle']"
    wait: timeouts.browser.small
  person_name_input:
    xpath: ".//*[@id='wt35_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wtPerson_Name']"
    wait: timeouts.browser.small
  person_surname_input:
    xpath: ".//*[@id='wt35_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wtPerson_Surname']"
    wait: timeouts.browser.small
  person_date_of_birth:
    xpath: ".//*[@id='wt35_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wtPerson_DateOfBirth']"
    wait: timeouts.browser.small
  save_person:
    xpath: "//*[@id='wt35_OutSystemsUIWeb_wt2_block_wtContent_wtMainContent_wt17']"
    wait: timeouts.browser.small