locators:
  new_person:
    xpath: ".//*[@id='wt17_OutSystemsUIWeb_wt2_block_wtContent_wtActions_wt4']"
    wait: timeouts.browser.small
  person_name:
    xpath: ".//td[contains(@class, 'TableRecords')]//a[contains(text(),'$0')]"
    wait: timeouts.browser.small
  person_saved_success:
    xpath: ".//div[@class='Feedback_Message_Success']"
    wait: timeouts.browser.medium
