movie_loading: Out Systems Demo Page Loading
#register_page_loading: Leroy Merlin Register Page Loading
#login_page_loading: Leroy Merlin Login Page Loading
#leroy_login: Leroy Merlin Login
#tempmail_home_loading: Temporary E-mail Home Page Loading
#retrieve_password_page_loading:  Leroy Merlin Retrieve Page Loading
#catalog_loading: Leroy Merlin Product Catalog Loading
#product_page_loading: Leroy Merlin Product Page Loading
#register_account_confirmation_loading: Leroy Merlin Account Confirmation Loading
#shopping_cart_loading: Leroy Merlin Shopping Cart Page Loading
#checkout_loading: Leroy Merlin Checkout Page Loading